### ISSUE TITLE
Gender doesn't stay saved

### ISSUE THREAD

**Issue by lambdakilo** [jannunen/f7_problemator#4]
After saving a gender, http 200 and http 204 the app doesn't show gender as set after reload.
![image](https://github.com/jannunen/f7_problemator/assets/31825085/286b783e-feaa-42a6-bd6a-8f70e90f2f50)

**Comment by lambdakilo** [comment]
Same for age

**Comment by jannunen** [comment]
Can you send me the CURL request, so it's faster to check what's going wrong.
